# fly.toml app configuration file generated for test-morning-firefly-9015 on 2025-09-02T12:08:09+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-morning-firefly-9015'
primary_region = 'nrt'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[build]
builder = "Dockerfile"