name: CD - Deploy to Fly.io

on:
  push:
    branches:
      - main   # main 브랜치에 push 될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test --no-daemon

#  test:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Run tests
#        run: ./gradlew test --no-daemon
#        env:
#          SPRING_PROFILES_ACTIVE: test

  deploy:
    runs-on: ubuntu-latest
    needs: [build] #, test]   # build & test 성공해야 실행
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
