name: CI - Build & Test

on:
  push:
    branches:
      - develop   # develop 브랜치에 push 될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

  test:
    runs-on: ubuntu-latest
    needs: build   # build가 끝나야 실행됨
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: ./gradlew test --no-daemon
